fixed_layers: [ ]
depth_multiple: 1.0
width_multiple: 1.0
img_size: 224
drop_pos: [ ]

architecture:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 32, 3 ] ],
    [ -1, 3, Hourglass, [ 64 ] ],

    # [ -2, 1, nn.MaxPool2d, [ 2, 2 ] ],
    [ -2, 5, CspOSA, [ 64 ] ],

    [ -1, 1, Conv, [ 128, 3 ] ],

    [ -1, 1, Conv, [ 128, 7 ] ],
    [ -1, 1, Conv, [ 128, 5 ] ],
    [ -1, 1, Conv, [ 128, 3 ] ],
    [ -1, 1, Conv, [ 128, 1 ] ],
    [ -1, 1, MobileOne, [ 128 ] ],
  ]
