fixed_layers: [ -2 ]
depth_multiple: 1.0
width_multiple: 0.5
img_size: 512

architecture:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 64, 3, 2 ] ],
    [ -1, 1, Conv, [ 64, 3 ] ],
    [ -1, 1, Conv, [ 128, 3 ] ],
    [ -1, 1, nn.MaxPool2d, [ 2 ] ],

    [ -1, 4, CspOSA, [ 128 ] ],
    [ -1, 1, nn.MaxPool2d, [ 2 ] ],

    [ -1, 4, Hourglass, [ 256 ] ],
    [ -1, 4, Hourglass, [ 384 ] ],
    [ -1, 4, Hourglass, [ 512 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 6, 1 ] ],
    [ -1, 1, Squeeze, [ ] ]
  ]
