fixed_layers: [ -2 ]
in_channels: 1
depth_multiple: 1.0
width_multiple: 1.0
img_size: 28

architecture:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 8, 3, 2 ] ],
    [ -1, 1, Conv, [ 16, 3 ] ],
    [-1, 1, nn.MaxPool2d, [ 2, 2 ] ],

    [ -1, 3, CspOSA, [ 16, 3 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 10, 1 ] ],
    [ -1, 1, Squeeze, [ ] ]
  ]
