fixed_layers: [ -2 ]
depth_multiple: 1.0
width_multiple: 1.0
img_size: 608
drop_pos: [ 6, 9, 12 ]

architecture:
  # [from, number, module, args]
  [ [ -1, 1, RepConv, [ 64, [ 1, 3 ], 2 ] ],
    [ -1, 2, RepConv, [ 64, [ 0, 1, 3 ] ] ],

    [ -1, 1, RepConv, [ 128, [ 1, 3 ], 2 ] ],
    [ -1, 3, RepConv, [ 128, [ 0, 1, 3 ] ] ],

    [ -1, 1, RepConv, [ 256, [ 1, 3 ], 2 ] ],
    [ -1, 4, RepConv, [ 256, [ 0, 1, 3 ] ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, RepConv, [ 384, [ 1, 3 ], 2 ] ],
    [ -1, 4, RepConv, [ 384, [ 0, 1, 3 ] ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, RepConv, [ 512, [ 1, 3 ], 2 ] ],
    [ -1, 4, RepConv, [ 512, [ 0, 1, 3 ] ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 6, 1 ] ],
    [ -1, 1, Squeeze, [ ] ]
  ]
