fixed_layers: [ -2 ]
depth_multiple: 1.0
width_multiple: 1.0
img_size: 608
drop_pos: [ 5, 8 ]

architecture:
  # [from, number, module, args]
  [ [ -1, 1, RepConv, [ 64, [ 1, 3 ], 2 ] ],

    [ -1, 1, RepConv, [ 64, [ 1, 3 ], 2 ] ],
    [ -1, 3, RepConv, [ 64, [ 0, 1, 3 ] ] ],

    [ -1, 1, RepConv, [ 128, [ 1, 3 ], 2 ] ],
    [ -1, 5, RepConv, [ 128, [ 0, 1, 3 ] ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, RepConv, [ 256, [ 1, 3 ], 2 ] ],
    [ -1, 15, RepConv, [ 256, [ 0, 1, 3 ] ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, RepConv, [ 1280, [ 1, 3 ], 2 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 6, 1 ] ],
    [ -1, 1, nn.Flatten, [ ] ]
  ]
