fixed_layers: [ -2 ]
depth_multiple: 1.0
width_multiple: 0.5
img_size: 512
drop_pos: [ 6, 9, 12 ]

architecture:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 64, 7, 2 ] ],
    [ -1, 1, nn.MaxPool2d, [ 3, 2 ] ],

    [ -1, 1, Bottleneck, [ 256, 2 ] ],
    [ -1, 2, Bottleneck, [ 256 ] ],

    [ -1, 1, Bottleneck, [ 512, 2 ] ],
    [ -1, 3, Bottleneck, [ 512 ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, Bottleneck, [ 1024, 2 ] ],
    [ -1, 5, Bottleneck, [ 1024 ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, Bottleneck, [ 2048, 2 ] ],
    [ -1, 2, Bottleneck, [ 2048 ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 7, 1 ] ],
    [ -1, 1, nn.Flatten, [ ] ]
  ]
