fixed_layers: [ -2 ]
depth_multiple: 1.0
width_multiple: 0.5
img_size: 512
drop_pos: [ 6, 9, 12 ]

architecture:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 64, 5, 2 ] ],
    [ -1, 1, nn.MaxPool2d, [ 3, 2 ] ],

    [ -1, 1, Conv, [ 64, 3 ] ],
    [ -1, 2, Bottleneck, [ 64 ] ],

    [ -1, 1, Conv, [ 128, 3, 2 ] ],
    [ -1, 3, Bottleneck, [ 128 ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, Conv, [ 256, 3, 2 ] ],
    [ -1, 5, Bottleneck, [ 256 ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, Conv, [ 512, 3, 2 ] ],
    [ -1, 2, Bottleneck, [ 512 ] ],
    [ -1, 1, DropBlock, [ 5, 0.1 ] ],

    [ -1, 1, nn.AdaptiveAvgPool2d, [ 1 ] ],
    [ -1, 1, nn.Conv2d, [ 7, 1 ] ],
    [ -1, 1, Squeeze, [ ] ]
  ]
