epochs: 150
batch_size: 32
device: ''
optimizer: SGD

lr0: 0.001  # initial learning rate (SGD=1E-2, Adam=1E-3)
lrf: 0.01  # final OneCycleLR learning rate (lr0 * lrf)
weight_decay: 0.0005  # optimizer weight decay 5e-4

hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
hsv_v: 0.4  # image HSV-Value augmentation (fraction)

gb_kernel: 5  # kernel_size of GuassianBlur

flipud: 0.  # image flip up-down (probability)
fliplr: 0.5  # image flip left-right (probability)

