depth_multiple: 1.0
width_multiple: 0.75

architecture:
  # [from, number, module, args]
  [ [ -1, 1, Conv, [ 64, 3, 2 ] ],  # 0-P1/2

    [ -1, 1, Conv, [ 128, 3, 2 ] ],  # 1-P2/4
    [ -1, 2, ELA, [ 128 ] ],

    [ -1, 1, Conv, [ 256, 3, 2 ] ],  # 3-P3/8
    [ -1, 2, ELA, [ 256 ] ],

    [ -1, 1, Conv, [ 512, 3, 2 ] ],  # 5-P4/16
    [ -1, 2, ELA, [ 512 ] ],

    [ -1, 1, Conv, [ 768, 3, 2 ] ],  # 7-P5/32
    [ -1, 2, ELA, [ 768 ] ],

    [ -1, 1, Conv, [ 1024, 3, 2 ] ],  # 9-P6/64
    [ -1, 2, ELA, [ 1024 ] ],


    [ -1, 1, SPPF, [ 512 ] ],
    [ -1, 1, Conv, [ 384, 1, 1 ] ],

    [ -1, 1, Upsample, [ 2 ] ],
    [ 8, 1, Conv, [ 384, 1, 1 ] ], # route backbone P5
    [ [ -1, -2 ], 1, Concat, [ ] ],

    [ -1, 4, CSP_OSA, [ 384 ] ], # 16
    [ -1, 1, Conv, [ 256, 1, 1 ] ],

    [ -1, 1, Upsample, [ 2 ] ],
    [ 6, 1, Conv, [ 256, 1, 1 ] ], # route backbone P4
    [ [ -1, -2 ], 1, Concat, [ ] ],

    [ -1, 4, CSP_OSA, [ 256 ] ], # 21
    [ -1, 1, Conv, [ 128, 1, 1 ] ],

    [ -1, 1, Upsample, [ 2 ] ],
    [ 4, 1, Conv, [ 128, 1, 1 ] ], # route backbone P3
    [ [ -1, -2 ], 1, Concat, [ ] ],


    [ -1, 4, CSP_OSA, [ 128 ] ], # 26
    [ -1, 1, Conv, [ 256, 3, 2 ] ],
    [ [ -1, 22 ], 1, Concat, [ ] ],  # cat

    [ -1, 4, CSP_OSA, [ 256 ] ], # 29
    [ -1, 1, Conv, [ 384, 3, 2 ] ],
    [ [ -1, 17 ], 1, Concat, [ ] ],  # cat

    [ -1, 4, CSP_OSA, [ 384 ] ], # 32
    [ -1, 1, Conv, [ 512, 3, 2 ] ],
    [ [ -1, 12 ], 1, Concat, [ ] ],  # cat

    [ -1, 4, CSP_OSA, [ 512 ] ], # 35


    [ 26, 1, Conv, [ 256, 3 ] ],
    [ 29, 1, Conv, [ 512, 3 ] ],
    [ 32, 1, Conv, [ 768, 3 ] ],
    [ 35, 1, Conv, [ 1024, 3 ] ],

    [ 26, 1, Conv, [ 320, 3 ] ],
    [ 21, 1, Conv, [ 640, 3 ] ],
    [ 16, 1, Conv, [ 960, 3 ] ],
    [ 11, 1, Conv, [ 1280, 3 ] ],

    [ [ -8,-7,-6,-5,-4,-3,-2,-1 ], 1, IAuxDetect, [ 20 ] ],   # Detect(P3, P4, P5, P6)
  ]
